export type Genre =
  | 'romance'
  | 'sci-fi-fantasia'
  | 'suspense-thriller'
  | 'nao-ficcao-autoajuda'
  | 'negocios'
  | 'saude'
  | 'biografia'
  | 'infantil'
  | 'espiritualidade'
  | 'poesia'

export const GENRE_LABELS: Record<Genre, string> = {
  romance: 'Romance',
  'sci-fi-fantasia': 'Ficção Científica / Fantasia',
  'suspense-thriller': 'Suspense / Thriller',
  'nao-ficcao-autoajuda': 'Não-Ficção / Autoajuda',
  negocios: 'Negócios / Empreendedorismo',
  saude: 'Saúde / Bem-estar',
  biografia: 'Biografia / Memórias',
  infantil: 'Infantil / Juvenil',
  espiritualidade: 'Espiritualidade',
  poesia: 'Poesia / Literatura',
}

export const GENRE_KEYWORDS: Record<Genre, string[]> = {
  romance: [
    'romance contemporâneo segunda chance',
    'livro de amor e superação',
    'romance com final feliz HEA',
    'história de amor proibido adulto',
    'romance emocional personagens reais',
    'livro para fãs de romance adulto',
    'romance de casal improvável',
    'história de amor e redenção',
    'romance com tensão slow burn',
    'livro de romance apaixonante brasil',
    'romance drama emocional intenso',
    'amor e segredos família romance',
  ],
  'sci-fi-fantasia': [
    'ficção científica brasileira indie',
    'fantasia épica magia e guerra',
    'sci-fi distopia futuro sombrio',
    'fantasia urbana brasil contemporâneo',
    'livro de fantasia para adultos',
    'aventura ficção científica espacial',
    'mundos mágicos sistema de magia',
    'fantasia de alta magia épica',
    'ficção científica pós-apocalíptico',
    'fantasia com heróis improvável',
    'sci-fi com inteligência artificial',
    'portal fantasy mundos paralelos',
  ],
  'suspense-thriller': [
    'thriller psicológico perturbador',
    'suspense policial investigação crime',
    'thriller mistério e segredos sombrios',
    'livro de suspense page-turner',
    'crime e investigação policial brasil',
    'thriller reviravolta surpreendente',
    'suspense narrador não confiável',
    'mistério assassinato detetive particular',
    'thriller jurídico advogado crime',
    'suspense familiar segredos obscuros',
    'thriller espionagem conspiração',
    'livro de mistério atmosférico tenso',
  ],
  'nao-ficcao-autoajuda': [
    'autoajuda desenvolvimento pessoal',
    'livro hábitos e produtividade',
    'mentalidade de crescimento mindset',
    'transformação de vida prática',
    'psicologia comportamental aplicada',
    'autoajuda para mulheres fortes',
    'guia prático de mudança de vida',
    'motivação e resiliência pessoal',
    'autoconhecimento inteligência emocional',
    'hábitos rotina sucesso diário',
    'bem-estar mental saúde emocional',
    'não ficção inspiracional verdadeiro',
  ],
  negocios: [
    'empreendedorismo brasil pequeno negócio',
    'marketing digital para iniciantes',
    'negócios online renda passiva',
    'gestão empresarial estratégia prática',
    'startup fundadores lições aprendidas',
    'vendas e persuasão técnicas práticas',
    'finanças pessoais investimento brasil',
    'liderança gestão de equipes alto',
    'marketing de conteúdo redes sociais',
    'empreender do zero capital mínimo',
    'copywriting vendas textos persuasivos',
    'e-commerce loja online sucesso',
  ],
  saude: [
    'saúde e bem-estar guia completo',
    'alimentação saudável dieta prática',
    'fitness treino em casa iniciante',
    'saúde mental ansiedade autoajuda',
    'meditação mindfulness para iniciantes',
    'emagrecimento saudável sem sofrimento',
    'exercício físico longevidade saúde',
    'qualidade do sono descanso hábitos',
    'nutrição funcional corpo saudável',
    'bem-estar holístico natural prático',
    'saúde hormonal equilíbrio feminino',
    'receitas saudáveis rápidas práticas',
  ],
  biografia: [
    'biografia inspiradora superação pessoal',
    'memórias de vida lições aprendidas',
    'autobiografia empreendedor brasileiro',
    'história de vida real emocionante',
    'memórias de guerra e resistência',
    'história de família e gerações',
    'diário de vida aprendizados práticos',
    'história verdadeira superação adversidade',
    'memórias infância brasil interior',
    'autobiografia mulher forte resiliente',
    'relato real transformação de vida',
    'saga familiar brasil história real',
  ],
  infantil: [
    'livro infantil ilustrado 3 a 6 anos',
    'história para dormir crianças',
    'livro juvenil aventura fantasia',
    'história infantil valores educação',
    'livro crianças 7 a 10 anos',
    'literatura infantil brasileira',
    'jovem adulto YA romance aventura',
    'livro infantil diversidade inclusão',
    'fábula infantil com lição moral',
    'aventura juvenil amizade coragem',
    'história de animais para crianças',
    'livro infantil primeiras palavras',
  ],
  espiritualidade: [
    'espiritualidade prática vida cotidiana',
    'meditação e conexão interior paz',
    'espiritualidade cristã fé esperança',
    'religiões afro-brasileiras umbanda',
    'lei da atração manifestação prática',
    'espiritualidade oriental budismo zen',
    'autoconhecimento alma espírito cura',
    'oração fé cura espiritual poder',
    'espiritualidade e ciência consciência',
    'anjos guias espirituais proteção',
    'cura interior jornada espiritual',
    'espiritualidade nova era energia',
  ],
  poesia: [
    'poesia contemporânea brasileira indie',
    'poemas de amor saudade distância',
    'poesia marginal urbana cotidiano',
    'crônicas contos literatura brasileira',
    'poesia feminista mulheres vozes',
    'literatura periférica brasil real',
    'poesia existencial vida e morte',
    'poesia de protesto e resistência',
    'contos fantásticos realismo mágico',
    'prosa poética beleza linguagem',
    'haiku poesia minimalista natureza',
    'antologia poemas temas variados',
  ],
}
